language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "YDXvF9lKDjAMNFfhSqIcQg"